version: "3.8"

services:
  app:
    build: .
    container_name: express-app
    expose:
      - "5000"

  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
